### ISSUE TITLE
Metastore Unit Test File stores absolute path to ktr - pls make relative or support variables

### ISSUE THREAD

**Issue by diethardsteiner** [mattcasters/pentaho-pdi-dataset#6]
Since projects usually involve multiple environments, paths have to be flexible. Currently the metastore unit test file specifies an absolut path for the ktr file. Please either allow the use of variables/parameters or at least a relative path.

**Comment by mattcasters** [comment]
This is a good point but a relative path does pose serious problems for finding a transformation from the viewpoint of the unit test.  So perhaps a possible solution is to set a base folder in the unit test?  The filename stored in the unit test metastore object would then be relative to that path.  I guess for repositories the problem is not present as much.

**Comment by diethardsteiner** [comment]
Yes, setting a base folder path in the unit test would be great. With parameter support please ;)

**Comment by mattcasters** [comment]
Very similar to #15

**Comment by mattcasters** [comment]
Added base path option and implemented variable UNIT_TESTS_BASE_PATH

**Comment by mattcasters** [comment]
Also logged when saving:

2018/11/07 09:51:58 - General - Unit test 'graph-output-test UT' : Saved relative path to transformation: ./graph-output-test1.ktr
